return function()
  require("modules.utf8")

  describe("utf8", function()
    describe("utf8len", function()
      it("returns the correct length", function()
        assert_equal(0, string.utf8len(""))
        assert_equal(3, string.utf8len("abc"))
        assert_equal(3, string.utf8len("åäó"))
        assert_equal(11, string.utf8len("foo åäó bar"))
        assert_equal(1, string.utf8len("😀"))
      end)
    end)

    describe("utf8upper", function()
      it("returns the uppercase string", function()
        assert_equal("", string.utf8upper(""))
        assert_equal("ABC", string.utf8upper("abc"))
        assert_equal("ÅÄÓ", string.utf8upper("åäó"))
        assert_equal("FOO ÅÄÓ BAR", string.utf8upper("foo åäó bar"))
        assert_equal("😀", string.utf8upper("😀"))
      end)
    end)

    describe("utf8lower", function()
      it("returns the lowercase string", function()
        assert_equal("", string.utf8lower(""))
        assert_equal("abc", string.utf8lower("ABC"))
        assert_equal("åäó", string.utf8lower("ÅÄÓ"))
        assert_equal("foo åäó bar", string.utf8lower("FOO ÅÄÓ BAR"))
        assert_equal("😀", string.utf8lower("😀"))
      end)
    end)
  end)
end
