local navigation = require("modules.navigation")
local utils = require("modules.utils")
local ui = require("ui.ui")

function init(self)
  ui.set_render_order_debug()

  self.debug_text = gui.get_node("debug/text")
  gui.set_enabled(self.debug_text, utils.is_debug())
end

function update(self, dt)
  if gui.is_enabled(self.debug_text) then
    gui.set_text(self.debug_text, navigation.dump_stack())
  end
end
