name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request:
    name: Pull Request
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        env:
          APP_VERSION: "0.0.1"
        run: |
          make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dist/**/*.dmg
            dist/**/*.zip
