name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  pull_request:
    name: Pull Request
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup
        with:
          macos_team_id: ${{ secrets.MACOS_TEAM_ID }}
          macos_apple_id: ${{ secrets.MACOS_APPLE_ID }}
          macos_certificate: ${{ secrets.MACOS_CERTIFICATE }}
          macos_certificate_password: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
          macos_keychain_password: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
          macos_notarytool_password: ${{ secrets.MACOS_NOTARYTOOL_PASSWORD }}

      - name: Build
        env:
          DEFOLD_PRIVATE_USERNAME: ${{ secrets.DEFOLD_PRIVATE_USERNAME }}
          DEFOLD_PRIVATE_TOKEN: ${{ secrets.DEFOLD_PRIVATE_TOKEN }}
          MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
        run: make all APP_VERSION=0.0.1

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dist/**/*.dmg
            dist/**/*.zip
