name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          BUTLER_PROJECT: ${{ secrets.BUTLER_PROJECT }}
        run: |
          make test
          make release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dist/**/*.dmg
            dist/**/*.zip
